import ExcelJS from 'exceljs'
import { saveAs } from 'file-saver'
import jsPDF from 'jspdf'
import 'jspdf-autotable'
import { format } from 'date-fns'

export const exportToCSV = async (data, filename) => {
    const workbook = new ExcelJS.Workbook()
    const worksheet = workbook.addWorksheet('Sheet1')

    if (data.length > 0) {
        worksheet.columns = Object.keys(data[0]).map(key => ({ header: key, key: key }))
    }

    worksheet.addRows(data)

    const buffer = await workbook.csv.writeBuffer()
    const blob = new Blob([buffer], { type: 'text/csv;charset=utf-8' })
    saveAs(blob, `${filename}.csv`)
}

export const exportToExcel = async (data, filename) => {
    const workbook = new ExcelJS.Workbook()
    const worksheet = workbook.addWorksheet('Data')

    if (data.length > 0) {
        worksheet.columns = Object.keys(data[0]).map(key => ({ header: key, key: key }))
    }

    worksheet.addRows(data)

    const buffer = await workbook.xlsx.writeBuffer()
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
    saveAs(blob, `${filename}.xlsx`)
}

export const exportPortfolioToPDF = (portfolio, profile) => {
    const doc = new jsPDF()

    // Title
    doc.setFontSize(20)
    doc.setTextColor(217, 119, 6) // Gold color
    doc.text('VinaGold AI - Portfolio Report', 14, 22)

    // User Info
    doc.setFontSize(12)
    doc.setTextColor(100)
    doc.text(`User: ${profile?.display_name || 'N/A'}`, 14, 32)
    doc.text(`Date: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, 14, 38)

    // Table
    const tableColumn = ["Asset", "Type", "Amount", "Buy Price", "Current Price", "Profit/Loss"]
    const tableRows = []

    portfolio.forEach(item => {
        const profit = (item.currentPrice - item.avgBuyPrice) * item.amount
        const profitColor = profit >= 0 ? [0, 128, 0] : [255, 0, 0] // Green or Red (not supported directly in simple array, simplifies to text)

        const row = [
            item.assetName,
            item.type,
            item.amount,
            `${item.avgBuyPrice.toLocaleString()} VND`,
            `${item.currentPrice.toLocaleString()} VND`,
            `${profit.toLocaleString()} VND`
        ]
        tableRows.push(row)
    })

    doc.autoTable({
        head: [tableColumn],
        body: tableRows,
        startY: 50,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [217, 119, 6] }
    })

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 20, doc.internal.pageSize.height - 10)
        doc.text('Generated by VinaGold AI', 14, doc.internal.pageSize.height - 10)
    }

    doc.save('gold_portfolio_report.pdf')
}
